title: "UK Newspaper Front Pages"
description: "Daily front page covers of major British newspapers."
theme: minima

# Output feed automatically using GitHub Pages' standard jekyll-feed plugin
plugins:
  - jekyll-feed

# Disable default Jekyll post processing for pure static rendering
permalink: pretty